### ISSUE TITLE
Support Elide 7.x

### ISSUE THREAD

**Issue by manosbatsis** [chirdeeptomar/refine-elide-rest#2]
This doesn't seem to work with Elide v7:

```
java.lang.IllegalArgumentException: Invalid character found in the request target [/api/account?page[offset]=0&page[limit]=10&page[totals]=0 ]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.9.jar:10.1.9]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

The URL generated by the data provider and resulting to the above error is :

/account?page[offset]=0&page[limit]=10&page[totals]&&

The right URL is bellow (although the ending && seems redundant)

/account?page%5Boffset%5D=0&page%5Blimit%5D=10&page%5Btotals%5D&&

**Comment by chirdeeptomar** [comment]
@manosbatsis Thanks for reporting it, the library doesn't support Elide 7 yet.

**Comment by chirdeeptomar** [comment]
Support added for Elide 7 on branch [feature/v7-support](https://github.com/chirdeeptomar/refine-elide-rest/tree/feature/v7-support)
